### ISSUE TITLE
Items disappear from Curios API Slots

### ISSUE THREAD

**Issue by MrAmericanMike** [blay09/InventoryEssentials#43]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

NeoForge

### Mod Loader Version

NeoForge 47.1.106

### Mod Version

1.20.1-8.2.6

### Balm Version

1.20.1-7.3.7

### Describe the Issue

I'll link to the Issue reported on Curios Issue Tracker as we are not sure which mod is the main cause for this to happen. But a combination of Curios, Inventory Essentials and Inventory Sorter.

https://github.com/TheIllusiveC4/Curios/issues/391

**Comment by BlayTheNinth** [comment]
Since the issue happens on sorting which is done by Inventory Sorter, while Inventory Essentials is as non-intrusive as it can and only ever acts when any of its keybinds are triggered, I don't think this is something that can be fixed on this side. 

Combined with the fact that Curios has been discontinued as of Minecraft 1.21, closing the issue here. Of course others are free to investigate this further but I really don't see any way that Inventory Essentials could be affecting sorting mods.
