### ISSUE TITLE
Shift-scrolling doesn't work in creative inventory

### ISSUE THREAD

**Issue by mhzen** [blay09/InventoryEssentials#7]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.12.12

### Mod Version

4.0.0

### Describe the Issue

Shift-scrolling doesn't work in creative inventory

Tested with this only mod and its dependencies on multimc

### Logs

https://gist.github.com/wierham/32d2ba26d69371032ff2592eba18e11c

### Do you use any performance-enhancing mods (e.g. OptiFine)?

nope

**Comment by BlayTheNinth** [comment]
What does shift-scrolling do / what is it supposed to do?

**Comment by mhzen** [comment]
Sorry, i didn't realize you've responded, github doesn't sent notification for some reason.

I made a mistake in the issue, what i was meant to say was shift-clicking not scrolling. It's supposed to move them without having to click individually. It doesn't work in creative inventory when i made this issue.

**Comment by BlayTheNinth** [comment]
I fixed some weird behaviour that occurred when shift-clicking and dragging in the inventory screen, but I don't think the screen should have the same shift drag behaviour as other inventories. Vanilla already reserves shift to grant a stack instead of a single item, and I don't see much use case in moving an entire row of creative mode items into one's hotbar.
